##Ni puto caso y si no eliminalo;
server:
  port: 8500
  servlet:
    context-path: /formacion
usuario: ${USUARIO}
contra: ${CONTRA}
admin:
  user: ${USUARIO_ADMIN}
  pass: ${PWD_ADMIN}
spring:
  application:
    name: servicio-formacion
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${URL_EUREKA}
